<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => 'Доступ запрещен.',
    'Accommodation' => 'Размещение',
    'Add' => 'Добавить',
    'Adults' => 'Взрослые',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот елемент?',
    'Arrival date' => 'Дата прибытия',
    'Cancel' => 'Отмена',
    'Caption' => 'Название',
    'Category' => 'Категория',
    'Children' => 'Дети',
    'Code' => 'Код',
    'Consent to the processing of sent data' => 'Согласие на обработку отправленных данных',
    'Created at' => 'Добавлено',
    'Days amount' => 'Количество дней',
    'Delete' => 'Удалить',
    'Departure date' => 'Дата отъезда',
    'Description' => 'Описание',
    'Duplicate entry.' => 'Запись уже введена.',
    'First Name' => 'Имя',
    'Food' => 'Питание',
    'Funds' => 'Номера',
    'Hotel' => 'Отель',
    'Image' => 'Фото',
    'Kettle' => 'Чайник',
    'Last Name' => 'Фамилия',
    'Location' => 'Населенный пункт',
    'Minibar' => 'Холодильник',
    'Modified at' => 'Изменено',
    'Name' => 'Имя',
    'Order' => 'Заказ',
    'Person' => 'Человек',
    'Phone' => 'Телефон',
    'Position' => 'Позиция',
    'Price' => 'Цена',
    'Price is the same as a room' => 'Цена такая же как у номера',
    'Prices' => 'Цены',
    'Reservation details' => 'Детали заказа',
    'Restroom' => 'Санузел',
    'Room' => 'Номер',
    'Room Clearning' => 'Уборка',
    'Room Service' => 'Обслуживание в номере',
    'Rooms count' => 'Комнат',
    'Save' => 'Сохранить',
    'Sauna' => 'Сауна',
    'Select' => 'Выбрать',
    'Show' => 'Показывать',
    'Size' => 'Площадь',
    'Slug' => 'Слаг',
    'Slug may consists a-z, numbers and minus only.' => 'Сдаг может содержать символы a-z, числа и знак минус.',
    'Special requirements' => 'Специальные требования',
    'Submit' => 'Отправить',
    'The requested model does not exist.' => 'Запрошенная модель не существует.',
    'Thumb' => 'Фото',
    'Title' => 'Заголовок',
    'Treatment' => 'Лечение',
    'Update' => 'Изменить',
    'Value' => 'Значение',
    'Verification Code' => 'Код защиты от спама',
];
